@ECHO OFF

REM SET THE PATH TO YOUR FREEBASIC INSTALL DIR
SET FBPATH=D:\FreeBASIC-0.24.0-win32\

REM SET THE PATH TO YOUR IGUANACMS SOURCES DIR
SET SRCPATH=D:\IguanaCMS-master\

%FBPATH%fbc.exe %SRCPATH%ROOT\CGI-BIN\INDEX.BAS -lang qb
