@ECHO OFF

REM SET THE PATH TO YOUR FREEBASIC INSTALL DIR
SET FBPATH=E:\FreeBASIC-0.24.0-win32\

REM SET THE PATH TO YOUR IGUANACMS SOURCES DIR
SET SRCPATH=E:\IguanaCMS-src\

%FBPATH%fbc.exe %SRCPATH%ROOT\CGI-BIN\INDEX.BAS -lang qb
%FBPATH%fbc.exe %SRCPATH%ROOT\CGI-BIN\ADMIN.BAS -lang qb
